### ISSUE TITLE
doc problem?

### ISSUE THREAD

**Issue by arthurnl** [vitalets/combodate#13]
I do not see how I can use the methods as documented:

All methods can be called as $().editable('method', parameters). 

I would like to implement dynamic interaction between a start and enddate. So I need to be able to set the values.

ps the correct working of the lib depends very much on the correct release of jquery and momentjs. like moment.js 2.1.0 does not work, 2.4.0 does

**Comment by vitalets** [comment]
oh, it is docs bug for sure, thank you! 
it should be `$(element).combodate('method', parameters)`. I will fix in docs.

For dynamic iteraction you shoud use `setValue` method. 
Please have a look: http://jsfiddle.net/5m6gG/3/

I will also re-check with moment 2.1.0.

**Comment by TheBox193** [comment]
See #15 in for more info/tracking on moment 2.4.0 compatibility issue.
