### ISSUE TITLE
Change the 'empty' text when no date is assigned

### ISSUE THREAD

**Issue by rogergithubbing** [vitalets/combodate#14]
Hello,

I have a combodate with the initial value set to null, and the combodate is showing 'Empty' in Italic+red.

I would like to change this text to show 'Without date specified' with a black font.

How can I achieve this ?

Thanks in advance,

Roger

**Comment by vitalets** [comment]
hi, @rogertranchez 
your question is more about x-editable, but nyway you should just use `emptytext` parameter
Please checkout this fiddle:
http://jsfiddle.net/xBB5x/2907/

and close this issue if everything fine.
thx!

**Comment by rogergithubbing** [comment]
Thanks a lot, it worked !
