### ISSUE TITLE
Refresh <select> with valid days for each month

### ISSUE THREAD

**Issue by carazo** [vitalets/combodate#21]
This is a improvement. 

If you select for example 30th February, it appears marked in red, it could be great to prevent user to valid it, to directly refresh days in order to show: 1 to 28 (or 29 if is leap year).

**Comment by KaitaniLabs** [comment]
+1

**Comment by vitalets** [comment]
hi, this works if you set `smartDays: true` option

**Comment by carazo** [comment]
Oh, I didn't know it, thank you very much!

**Comment by vitalets** [comment]
Ok :) sorry for so late reply.

**Comment by carazo** [comment]
Don't worry, thank you!!!! It is a pleasure to have a so good support.
