### ISSUE TITLE
CSS / layout not applied to dropdown

### ISSUE THREAD

**Issue by maeishoj** [vitalets/combodate#27]
I am using the combodate 

<div id="div-date">
<input type="text" id="date" data-format="MM-YYYY" data-template="MMM YYYY" name="date">
</div>

and then setting attributes

$('#date').combodate({
         minYear: currentYear,
         maxYear: currentYear+10
});

However the bootstrap layout of buttons is not applied to it so it look ugly: http://puu.sh/aJJdf/dd30aeadd4.png

Can someone please explain me why?

**Comment by vitalets** [comment]
hi, is the issue still actual with current bootstrap?

**Comment by maeishoj** [comment]
You can close. I am not working on it anymore but I think i fixed it.

**Comment by vitalets** [comment]
okay, thank you!
