### ISSUE TITLE
HTML template for dates

### ISSUE THREAD

**Issue by istian** [vitalets/combodate#35]
Hi,

First, thanks for this simple yet very useful plugin. As for my question, is there a way to apply/set an html template for the date elements? Say, I'd like to add a label for each date elements like:

| Day | Month | Year |
| --- | --- | --- |
| comboday | cobomonth | comboyear |

Thanks

**Comment by vitalets** [comment]
hi

interesting case, but seems to be very specific. I think the best solution is just overwrite `getTemplate` method to return table with headers and selects.
Please have a look: http://jsfiddle.net/5m6gG/84/
