### ISSUE TITLE
0 and 12 for Hour

### ISSUE THREAD

**Issue by mrlife** [vitalets/combodate#4]
Hello!  Thank you for combodate!  Is it possible to suppress the 0 in the hour dropdown?  The reason is that if one selects 0 AM, it is interpreted as 12:00 AM.  If one selects 12 AM, it is interpreted as 12:00 PM!

Thank you!!!
Eric

**Comment by vitalets** [comment]
hi, yes it's good idea. 
The problem is known -  "Confusion at noon and midnight"
http://en.wikipedia.org/wiki/12-hour_clock

Btw, did you check what is the native behavior of momentjs for that?

**Comment by mrlife** [comment]
It appears to be default behavior of JavaScript dates: zero hour is midnight. I combed the momentjs docs and did not see where there was any option to change this behavior. I will try to come up with solution and will share if I am successful; please share if you are too!

Should be simple 1 to 12 when using am/pm.  No need for both 0 and 12 in that case. 12am and 12pm would be taken literally as midnight and noon, which eliminates confusion for user. I may be able to account for it with some additional javascript.

**Comment by vitalets** [comment]
just checked once more momentjs parse rules: 
00:00 pm, 12:00 pm --> 12:00 (24-h format, day not change)
00:00 am, 12:00 am --> 00:00 (24-h format, day not change)
