### ISSUE TITLE
make combodate disable-able

### ISSUE THREAD

**Issue by jo-soft** [vitalets/combodate#47]
hey guys

I stuck around with trying to disable a combodate input.  as far as i can see ng-disabled only acts on the input. but not on the following selects inside the span.
I cannot find any documentation or other bug report on this.

i'm using combodate 1.1.0

bg
Johannes

**Comment by jo-soft** [comment]
I'm sorry for confusion. the project where in which this  issue appeared did not use this library directly.

**Comment by samionder** [comment]
So is it possible enable / disable combodate?

**Comment by jo-soft** [comment]
@samionder  you can have a look here: https://github.com/jo-soft/combodate

It works if the element is disabled via disabled="foo". And i Implemented a function setDisabled to set the disabled status to true/false.

bg,
Johannes
