### ISSUE TITLE
Combodate default value

### ISSUE THREAD

**Issue by tanut-v** [vitalets/combodate#5]
How to set default value of combodate dropdowns to current date
![screen shot 2013-07-23 at 12 52 52 pm](https://f.cloud.github.com/assets/4558215/839873/2d48879c-f35c-11e2-8f64-e48c66ea9487.png)

but leave input value empty
![screen shot 2013-07-23 at 12 17 42 pm](https://f.cloud.github.com/assets/4558215/839791/50bab48e-f357-11e2-9ad7-068a17bf527b.png)

**Comment by vitalets** [comment]
I will add param `defaultValue` to the nearest release of x-editable.
thanks for pointing on that!

**Comment by tanut-v** [comment]
Very thanks!! :thumbsup: :thumbsup:

**Comment by vitalets** [comment]
`defaultValue` added in x-editable 1.4.6

**Comment by kevinap** [comment]
where should I put the defaultValue in the code?
thanks

**Comment by bipin244** [comment]
//for default value current value
`$('#date').combodate({
            value: moment().format('MM-DD-YYYY')
        });`
