### ISSUE TITLE
Multiple drop downs

### ISSUE THREAD

**Issue by sabotawsh** [vitalets/combodate#6]
I'm an amateur with javascript so my apologies if this is a stupid question, but how can I implement two drop downs (for #datetime24)? My code will only show one. The second shows an input field.

Example below will only work once in a list:

```
    <div class="event-item">
        <label for="date">End Date and Time</label>
        <input type="text" id="datetime24" data-format="DD-MM-YYYY HH:mm" data-template="DD / MM / YYYY     HH : mm" name="datetime" value="21-12-2012 20:30">
        <script>
            $(function(){
            $('#datetime24').combodate();  
            });
        </script>
    </div>
```

**Comment by vitalets** [comment]
It's strange, your code is working: http://jsfiddle.net/5m6gG/1/

**Comment by vitalets** [comment]
closing as too old.
please feel free to reopen if issue still exists.
